name: Build and Test Flask App

on:
  push:
    branches:
      - main
      - wsei-lab
  pull_request:
    branches:
      - main
      - wsei-lab

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: myuser
          MYSQL_PASSWORD: mypassword
          MYSQL_DATABASE: mydatabase
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Sprawdzenie kodu z repozytorium
      - name: Checkout code
        uses: actions/checkout@v3

      # Ustawienie środowiska Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Instalacja zależności
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flask mysql-connector-python

      # Czekanie, aż MySQL będzie gotowy
      - name: Wait for MySQL
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h mysql --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 5
          done

      # Uruchomienie testów
      - name: Run tests
        run: |
          python -m unittest discover -s tests
